# Generated by Django 5.2.4 on 2025-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_photoalbum_photogallery_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.CharField(choices=[('pre_primary', 'Pre Primary'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('higher_secondary', 'Higher Secondary')], default='primary', max_length=20),
        ),
    ]
