# Generated by Django 5.2.4 on 2025-07-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacher_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, help_text='Short about me section'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.TextField(blank=True, help_text='Education details'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True, help_text='Experience details'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pronouns',
            field=models.CharField(blank=True, help_text='e.g. she/her, he/him, they/them', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='teachers/resumes/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
