# Generated by Django 5.2.4 on 2025-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teacher_about_teacher_education_teacher_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.facebook.com/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com/'),
        ),
    ]
