# Generated by Django 5.2.4 on 2025-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_teacher_linkedin_remove_teacher_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagarmathaTeensClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('vice_secretary', 'Vice Secretary'), ('treasurer', 'Treasurer'), ('executive', 'Executive'), ('club_teacher', 'Club Teacher')], max_length=20)),
                ('photo', models.ImageField(upload_to='club/')),
                ('class_name', models.CharField(max_length=50, verbose_name='Class')),
                ('statement', models.TextField(blank=True, help_text='Statement for President, Secretary, and Club Teacher (for frontend only)')),
            ],
            options={
                'ordering': [models.Case(models.When(designation='president', then=0), models.When(designation='vice_president', then=1), models.When(designation='secretary', then=2), models.When(designation='vice_secretary', then=3), models.When(designation='treasurer', then=4), models.When(designation='executive', then=5), models.When(designation='club_teacher', then=6), default=7, output_field=models.IntegerField()), 'name'],
            },
        ),
    ]
