# Generated by Django 5.2.4 on 2025-07-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sagarmathateensclubmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagarmathateensclubmember',
            name='statement',
        ),
    ]
