# Generated by Django 5.2.4 on 2025-07-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_sagarmathateensclubmember_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagarmathateensclubmember',
            name='statement',
            field=models.TextField(blank=True, help_text='Statement for President, Secretary, and Club Teacher (for frontend only)'),
        ),
    ]
